---
plugin: aws_ec2 
regions:
  - us-east-1
filters:
  tag:awx_inventory: teste
  tag:awx_app: nginx
  instance-state-name : running

# tasks file for install_nginx
- name: Install packages
  package:
    name: "{{ webserver_packages }}"
    state: latest

- name: Add base NGINX configuration file
  copy:
    dest: /etc/nginx/nginx.conf
    src: etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: Reload NGINX

