---
# tasks file for deploy_nginx_app_v1
- name: Copiando novo arquivo de Conf V1
  template:
    src: usr/share/nginx/site.example.com
    dest: /usr/share/nginx/site.example.com
    owner: root
    group: root
    mode: 0644
  register: copy_new_content_v1

- name: Copiando novo conteudo site V1
  template:
    src: etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  register: copy_new_config_v1
  notify: Reload NGINX