name: Ansible-Integration
on:
  pull_request:
    types: [opened]
jobs:
  Ansible-Integration:
    if: github.event_name == 'pull_request_review_comment'
    runs-on: self-hosted
    steps:
        - name: Get Playbook Id from Ansible Tower
          if: startsWith( github.event.pull_request.title, 'playbook' )
          id: get_playbook_id
          run: echo "Teste OK"