name: Ansible-Integration
on:
  pull_request:
    types: [closed]
resolves:
  
jobs:
  Jenkins-Integration:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
        - name: Trigger Ansible Tower - Playbook teste
          uses: "swinton/httpie.action@master"
          args: 'POST", "https://ansible-awx-hmlg.moip.com.br/api/v2/job_templates/9/launch/", "Authorization:Bearer ${{ secrets.AWX_TOKEN }}"'