name: Ansible-Integration
on:
  pull_request:
    types: [closed]
jobs:
  Ansible-Integration:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
        - name: Get Job Id from Ansible Tower
          run: echo "::set-output name=playbook_id::$(curl -i -X GET -H 'Authorization:Bearer ${{ secrets.AWX_TOKEN }}' https://ansible-awx-hmlg.wirecard.int/api/v2/job_templates/?name=playbook_${{github.event.pull_request.title}}"
          id: get_playbook_id

        - name: Show id Playbook
          run: echo "Playbook ID is ${{ steps.get_playbook_id.outputs.playbook_id }}"