name: Ansible-Integration
on:
  pull_request:
    types: [closed]
jobs:
  Ansible-Integration:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
        - name: Get Job Id from Ansible Tower
          id: get_playbook_id
          run: echo "::set-output name=playbook_id::$(curl -ivk -X GET -H 'Authorization:Bearer ${{ secrets.AWX_TOKEN }}' https://ansible-awx-hmlg.wirecard.int/api/v2/job_templates/?name=playbook_${{github.event.pull_request.title}} )"

        - name: Show id Playbook
          run: |
              echo "${{ steps.get_playbook_id.outputs.playbook_id }}"
              echo "$(jq -r '.results')"