name: Ansible-Integration
on:
  pull_request_review_comment:
    types: [created]
jobs:
  Ansible-Integration:
    runs-on: self-hosted
    steps:
        - name: Get Playbook Id from Ansible Tower
          if: startsWith( github.event.pull_request.title, 'playbook' )
          id: get_playbook_id
          run: echo "Teste OK"