name: Ansible-Integration
on:
  issue_comment:
    types: [created]
jobs:
  Ansible-Integration:
    if: github.event.issue.pull_request
    runs-on: self-hosted
    steps:
        - name: Get Playbook Id from Ansible Tower
          if: contains( github.event.comment.body, 'playbook_run' )
          id: get_playbook_id
          run: echo "Teste OK "