name: Ansible-Integration
on:
  pull_request:
    types: [closed]
  
jobs:
  Jenkins-Integration:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
        - name: Trigger Ansible Tower - Playbook teste
          uses: docker://l3andro4mc/httpie:v1.0
          with:
            args: "--verify=no POST https://ansible-awx-hmlg.wirecard.int/api/v2/job_templates/9/launch/ 'Authorization:Bearer ${{ secrets.AWX_TOKEN }}'"