name: Playbook-Check
on:
  pull_request:
    types: [opened]
jobs:
  Playbook-Check:
    runs-on: self-hosted
    steps:
        - name: Ansible AWX - Set Parameters
          run: |
              echo "baseURL=https://ansible-awx-hmlg.wirecard.int" >> $GITHUB_ENV
              echo "playbook_Name=${{github.event.pull_request.title}}" >> $GITHUB_ENV
              echo "GITHUB_URL=${{ github.event.pull_request.comments_url }}" >> $GITHUB_ENV
              echo "GITHUB_TOKEN= ${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

        - name: Ansible AWX - Run Playbook in Check Mode
          uses: docker://l3andro4mc/ansible_awx_action:v1.0
          if: startsWith( github.event.pull_request.title, 'playbook' )
          with:
            args: ${{ env.baseURL }} ${{ secrets.AWX_TOKEN }} ${{ env.playbook_Name }} ${{ env.GITHUB_URL}} ${{ env.GITHUB_TOKEN}} check