name: Playbook-Apply
on:
  issue_comment:
    types: [created]
jobs:
  Playbook-Apply:
    if: github.event.issue.pull_request
    runs-on: self-hosted
    steps:        
        - name: Ansible AWX - Set Parameters
          run: |
              echo "baseURL=https://ansible-awx-hmlg.wirecard.int" >> $GITHUB_ENV
              echo "playbook_Name=${{github.event.issue.title}}" >> $GITHUB_ENV
              echo "GITHUB_URL=${{ github.event.issue.comments_url }}" >> $GITHUB_ENV
              echo "GITHUB_TOKEN= ${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

        - name: Ansible AWX - Playbook Check Mode
          uses: docker://l3andro4mc/ansible_awx_action:v1.0
          if: contains( github.event.comment.body, 'playbook_check' )
          with:
            args: ${{ env.baseURL }} ${{ secrets.AWX_TOKEN }} ${{ env.playbook_Name }} ${{ env.GITHUB_URL}} ${{ env.GITHUB_TOKEN}} check

        - name: Ansible AWX - Playbook Run Mode
          uses: docker://l3andro4mc/ansible_awx_action:v1.0
          if: contains( github.event.comment.body, 'playbook_run' )
          with:
            args: ${{ env.baseURL }} ${{ secrets.AWX_TOKEN }} ${{ env.playbook_Name }} ${{ env.GITHUB_URL}} ${{ env.GITHUB_TOKEN}} run